---
#### Install jdk_svr ###

- name: init_jdk_svr
  unarchive: src="../roles/sharestorage/apps/svr/jdk{{jdk_version}}.tar.gz" dest="/apps/svr/" owner=apps group=apps mode=0775
  tags:
    - init_jdk_svr

- name: link_jdk8
  file: src="/apps/svr/jdk{{jdk_version}}" dest="/apps/svr/jdk8" state=link force=yes group=apps owner=apps
  when: jdk_version == '1.8.0_172'
  tags:
    - link_jdk8

### Push_apps_env ###

- name: push_apps_env
  copy: src="apps_env.sh" dest="/apps/sh" owner=apps group=apps mode=0775
  when: push_apps_env == 'true'
  tags:
    - push_apps_env

- name: exec_env_sh
  shell: source /apps/sh/apps_env.sh
  when: push_apps_env == 'true'
  become: yes
  become_user: root

### Check_env ###
- name: check_env_apps
  shell: /usr/bin/grep -vE '^#' /home/apps/.bashrc |grep 'jdk8'|wc -l
  register: check_env_apps
  tags:
    - check_env_apps

- name: check_env_deployer
  shell: /usr/bin/grep -vE '^#' /home/deployer/.bashrc |grep 'jdk8'|wc -l
  register: check_env_deployer
  tags:
    - check_env_deployer

- name: check_env_all
  shell: /usr/bin/grep -vE '^#' /etc/profile |grep 'jdk8'|wc -l 
  register: check_env_all
  tags:
    - check_env_all

### Export_env ###

- name: push_env_file
  copy: src="jdk_env.sh" dest="/tmp" owner=apps group=apps
  tags:
    - push_env_file

- name: set_env_all
  shell: cat /tmp/jdk_env.sh >> /etc/profile
  when: setenv == 'all' and check_env_all.stdout == '0'
  tags: 
    - set_env_all
  become_user: root
  become: yes

- name: set_env_deployer
  shell: cat /tmp/jdk_env.sh >> /home/deployer/.bashrc
  when: setenv == 'deployer' and check_env_deployer.stdout == '0'
  tags: 
    - set_env_deployer
  become_user: root
  become: yes

- name: set_env_apps
  shell: cat /tmp/jdk_env.sh >> /home/apps/.bashrc
  when: setenv == 'apps' and check_env_apps.stdout == '0'
  tags:
    - set_env_apps

- name: remove_env_sh
  shell: rm -rf /tmp/jdk_env.sh
  tags:
    - remove_env_sh 

- name: exec_env_all
  shell: source /etc/profile
  when: setenv == 'all'
  tags:
    - exec_env

- name: exec_env_deployer
  shell: source /home/deployer/.bashrc
  when: setenv == 'deployer'
  tags:
    - exec_env

- name: exec_env_apps
  shell: source /home/apps/.bashrc
  when: setenv == 'apps'
  tags:
    - exec_env
