---
#zookeeper_hosts: [{"host":10.154.2.94,"id":1},{"host":10.154.2.95,"id":2}]


## General
zookeeper_version: 3.4.14

## Service options

# Owner
zookeeper_user: apps
zookeeper_group: apps

# start on boot
zookeeper_service_enabled: 'yes'
# current state: started, stopped
zookeeper_service_state: started

# Files & Paths
zookeeper_data_dir: /apps/data/zookeeper_{{ zookeeper_client_port }}
zookeeper_log_dir: /apps/logs/zookeeper_{{ zookeeper_client_port }}
zookeeper_data_log_dir: "{{ zookeeper_log_dir }}"
zookeeper_install_path: /opt/zookeeper
zookeeper_conf_dir: "/apps/conf/zookeeper_{{ zookeeper_client_port }}"


# Connection properties
# Deprecated
client_port: 2181
# Deprecated
init_limit: 5
# Deprecated
sync_limit: 2
# Deprecated
tick_time: 2000
zookeeper_client_port: "{{ client_port }}"
zookeeper_init_limit: "{{ init_limit }}"
zookeeper_sync_limit: "{{ sync_limit }}"
zookeeper_tick_time: "{{ tick_time }}"
zookeeper_elect_port: 3888
zookeeper_cluster_port: 2888

zookeeper_autopurge_purgeInterval: 0
zookeeper_autopurge_snapRetainCount: 10

# Java options
zookeeper_jmx_enabled: true
zookeeper_jmx_port: 9999
zookeeper_java_opts: "-Djava.net.preferIPv4Stack=true"

# Rolling file appender setttings
zookeeper_rolling_log_file_max_size: 100MB
zookeeper_max_rolling_log_file_count: 10



# Dict of ENV settings to be written into the (optional) conf/zookeeper-env.sh
zookeeper_env: {}

# Controls Zookeeper myid generation
zookeeper_force_myid: true

zookeeper_force_reinstall: false

zookeeper_4lw_commands_whitelist: stat

#
# You can add more zookeper config options using zookeeper_config_map
#
# zookeeper_config_map:
#  - key: traceFile
#    value: zoo-trace.log
