---

#### Make sure YUM Packages
- name: init_yum_pkgs
  yum: name={{item}} state=present
  with_items: [rsync,tree,sudo,tar,gcc,gcc-c++,python-devel,wget]
  become: yes
  tags:
    - init_yum_pkgs

#### Initialize apps directory
- name: init_apps_dirs
  file: path=/apps/{{item}} state=directory owner=apps group=apps mode=0775
  with_items: [conf,data,lib,logs,run,sh,sharedstorage,svr,tools]
  become: yes
  become_user: root
  tags:
    - init_apps_dirs

#### Initialize sh directory
- name: init_apps_sh
  synchronize: mode=push src="apps/sh/" dest="/apps/sh" compress=yes owner=yes group=yes
  become: yes
  tags:
    - init_apps_sh

#### Init profile
- name: check_profile
  shell: /usr/bin/grep apps_env /etc/profile | wc -l
  register: profile_check
  tags:
    - check_profile

- name: insert_apps_env_profile
  become: yes
  shell: /usr/bin/echo 'source /apps/sh/apps_env.sh' >> /etc/profile
  when: profile_check.stdout == '0'

